### ISSUE TITLE
 brownie-config.yaml remappings bug

### ISSUE THREAD

**Issue by zgfzgf** [eth-brownie/brownie#1137]
### Environment information

* `brownie` Version: 1.14.6
* `solc` Version: 0.6.6
* Python Version: 3.8.10
* OS: ubuntu

```yaml
dependencies:
  - Uniswap/Uniswap-v2-core@1.0.0
  - Uniswap/Uniswap-lib@2.1.0


compiler:
  solc:
    version: 0.6.6
    remappings:
      - "@uniswapcore=Uniswap/Uniswap-v2-core@1.0.0"
      - "@uniswaplib=**Uniswap**/Uniswap-lib@2.1.0"
```

```
brownie compile 

contracts/UniswapV2Migrator.sol:3:1: ParserError: Source "Uniswap/Uniswap-lib@2.1.0/contracts/libraries/TransferHelper.sol" not found: File not found.
import '@uniswaplib/contracts/libraries/TransferHelper.sol'
```

```
make .brownie/packages/Uniswaplib
mv  Uniswap/Uniswap-lib@2.1.0 Uniswaplib
```

```yaml
compiler:
  solc:
    version: 0.6.6
    remappings:
      - "@uniswapcore=Uniswap/Uniswap-v2-core@1.0.0"
      - "@uniswaplib=**Uniswaplib**/Uniswap-lib@2.1.0"
```

brownie compile  OK
