### ISSUE TITLE
Include storageLayout with compiled artifacts

### ISSUE THREAD

**Issue by realisation** [eth-brownie/brownie#1212]
### Overview
I want to be able to get the JSON of the storage layout in my artifacts, just like the ABI, etc. Since Brownie pulls in dependencies from various places, it is difficult to get the storage layout because since Brownie does not offer a way to include it in the artifacts, currently the user needs to get all of the dependencies together in a flat directory and run solc on them that way. 
* What you are trying to do
Have Brownie include the storage layout in the artifacts. The brownie config could accept the compiler options, or this particular option, and include it in the artifacts 
* Why Brownie's current functionality is inadequate to address your goal
It doesn't do that 

### Specification

The brownie config could accept something like this:
```
compiler:
  solc:
    version: 0.8.2
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0"
    optimizer:
      enabled: true
      runs: 400
    outputSelection:
        "*": 
          "*": 
            - "storageLayout"
```
