### ISSUE TITLE
Cannot use ganache flags db or db_path in brownie config

### ISSUE THREAD

**Issue by realisation** [eth-brownie/brownie#1274]
### Environment information

* `brownie` Version: 1.16.2
* `ganache-cli` Version: 6.12.2
* `solc` Version: irrelevant
* Python Version: 3.9
* OS: mac

### What was wrong?

I wanted to use the db setting for ganache to give it a preloaded chainstate but I got the following error

`InvalidArgumentWarning: Ignoring invalid commandline setting for ganache-cli: "db" with value "./chainstate".`

This occurred when running a script of mine like

`brownie run scripts/myscript.py --network development`

with brownie config looking like

```
networks:
  default: development
  development:
    gas_limit: max
    cmd_settings:
      gas_limit: 9007199254740991
      db: "./chainstate"
```
