### ISSUE TITLE
Infura doesn't support Polygon

### ISSUE THREAD

**Issue by HarishTeens** [eth-brownie/brownie#1357]
https://github.com/eth-brownie/brownie/blob/0fa4477a178bd55b6683f60d077b7060df02b2c5/brownie/data/network-config.yaml#L101

Since Infura doesnt support Polygon. I had to add a new config with Alchemy URL. Think it would be better to simply use that in the default config to reduce hassle.

My suggested changes would simply be to rename Infura to Alchemy and use the appropriate host URL:
```
  - name: Polygon
    networks:
      - name: Mainnet (Alchemy)
        chainid: 137
        id: polygon-main
        host: https://polygon-mumbai.g.alchemy.com/v2/$WEB3_ALCHEMY_PROJECT_ID
        explorer: https://api.polygonscan.com/api
        multicall2: "0xc8E51042792d7405184DfCa245F2d27B94D013b6"
      - name: Mumbai Testnet (Alchemy)
        chainid: 80001
        id: polygon-test
        host: https://polygon-mumbai.g.alchemy.com/v2/$WEB3_ALCHEMY_PROJECT_ID
        explorer: https://api-testnet.polygonscan.com/api
        multicall2: "0x6842E0412AC1c00464dc48961330156a07268d14"
```
