### ISSUE TITLE
File not found, brownie-config.yaml dependencies didn't get installed

### ISSUE THREAD

**Issue by danivideda** [eth-brownie/brownie#1388]
### Environment information

* `brownie` Version: 1.17.2
* `ganache-cli` Version: 6.12.2
* `solc` Version: 0.6.12
* Python Version: 3.9.1
* OS: MacOS Monterey 12.1

### What was wrong?
Compiling contracts using `brownie compile` raise an error:
```bash
contracts/FundMe.sol:5:1: ParserError: Source "smartcontractkit/chainlink-brownie-contracts@1.1.1/contracts/src/v0.6/interfaces/AggregatorV3Interface.sol" not found: File not found.
import "@chainlink/contracts/src/v0.6/interfaces/AggregatorV3Interface.sol";
```
The source code:
- **FundMe.sol**
```solidity
import "@chainlink/contracts/src/v0.6/interfaces/AggregatorV3Interface.sol";
import "@chainlink/contracts/src/v0.6/vendor/SafeMathChainlink.sol";
```
- **brownie-config.yaml**
```yaml
dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
```

### How can it be fixed?

Installing brownie packages manually before running `brownie compile` solves the problem.
```zsh
brownie pm install smartcontractkit/chainlink-brownie-contracts@1.1.1
```
According to the [documentation](https://eth-brownie.readthedocs.io/en/stable/config.html#dependencies), the dependencies specified in **brownie-config.yaml** should be installed first before compiling any contracts
