### ISSUE TITLE
Cannot compile contract with block.basefee

### ISSUE THREAD

**Issue by BlinkyStitt** [eth-brownie/brownie#1467]
### Environment information

* `brownie` Version: 1.18.1
* `solc` Version: 0.8.12

### What was wrong?

```
>>> c = Contract.from_explorer("0xca11bde05977b3631167028862be2a173976ca11")
Fetching source of 0xcA11bde05977b3631167028862bE2a173976CA11 from api.etherscan.io...
CompilerError: solc returned the following errors:

TypeError: "basefee" is not supported by the VM version.
   --> Multicall3-flattened.sol:209:19:
    |
209 |         basefee = block.basefee;
    |                   ^^^^^^^^^^^^^

>>> CONFIG.settings['compiler']['evm_version']
'london'
```

### How can it be fixed?

I don't know. Is my compiler version not getting passed through to from_explorer?

**Comment by sandybradley** [comment]
Same issue:
```sh
$ brownie compile
Brownie v1.19.1 - Python development framework for Ethereum

Compiling contracts...
  Solc version: 0.8.16
  Optimizer: Enabled  Runs: 200
  EVM Version: Istanbul
CompilerError: solc returned the following errors:

TypeError: "basefee" is not supported by the VM version.
```

Error message from:
https://github.com/ethereum/solidity/blob/2ddb26ad96e851e55c57c90d4841967717db4eb8/libsolidity/analysis/TypeChecker.cpp#L3299

**Comment by WyseNynja** [comment]
> Same issue:
> 
> ```shell
> $ brownie compile
> Brownie v1.19.1 - Python development framework for Ethereum
> 
> Compiling contracts...
>   Solc version: 0.8.16
>   Optimizer: Enabled  Runs: 200
>   EVM Version: Istanbul
> CompilerError: solc returned the following errors:
> 
> TypeError: "basefee" is not supported by the VM version.
> ```
> 
> Error message from: https://github.com/ethereum/solidity/blob/2ddb26ad96e851e55c57c90d4841967717db4eb8/libsolidity/analysis/TypeChecker.cpp#L3299

Looks like you are set to Istanbul. Can you set your hard fork to London (or later) and try again?

**Comment by sandybradley** [comment]
Yes, that worked, thank you.
```toml
compiler:
    evm_version: london
    solc:
        version: 0.8.16
        optimizer:
            enabled: true
            runs: 20000
        remappings: null
```

**Comment by chhajershrenik** [comment]
The same issue persists when using module Contract.from_explorer, when writing tests.
How do I change the VM version in `input_json` for imported contracts.

![image](https://github.com/eth-brownie/brownie/assets/57632527/45fee65c-4e0d-4448-a142-7e25c6eee4f8)

For testing I'm importing the Entry point contract from the mainnet "0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789".

**Comment by chhajershrenik** [comment]
> The same issue persists when using module Contract.from_explorer, when writing tests. How do I change the VM version in `input_json` for imported contracts.
> 
> ![image](https://user-images.githubusercontent.com/57632527/255333280-45fee65c-4e0d-4448-a142-7e25c6eee4f8.png)
> 
> For testing I'm importing the Entry point contract from the mainnet "0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789".

```YAML
project_structure:
  build: brownie-build
networks:
  default: mainnet-fork
  mainnet-fork:
    verify: True
    cmd_settings:
      accounts: 20
      account_keys_path: "ganacheaccount.json"
      evm_version: "london"
autofetch_sources: True
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.8.3
  - uniswap/v3-core@1.0.0
  - uniswap/v2-core@1.0.1
  - uniswap/v3-periphery@1.3.0
  - uniswap/v2-periphery@1.0.0-beta.0
  - smartcontractkit/chainlink@2.1.1
  - uniswap/v2-periphery@1.0.0-beta.0
compiler:
  evm_version: "london"
  solc:
    optimizer:
      enabled: true
      runs: 20000
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.3'
      - '@uniswap/v3-core=uniswap/v3-core@1.0.0'
      - '@uniswap/v2-core=uniswap/v2-core@1.0.1'
      - '@uniswap/v3-periphery=uniswap/v3-periphery@1.3.0'
      - '@uniswap/v2-periphery=uniswap/v2-periphery@1.0.0-beta.0'
      - '@chainlink=smartcontractkit/chainlink@2.1.1'
```
