### ISSUE TITLE
Brownie pm is attempting to load `.env` from installed package

### ISSUE THREAD

**Issue by theref** [eth-brownie/brownie#1499]
### Environment information

* `brownie` Version: 1.18.1
* Python Version: 3.8.12
* OS: osx

### What was wrong?
My tests now fail after adding a `.env` file to my project and specifying that file in `brownie-config.yml`.
They fail when attempting to setup a fixture that utilises OpenZeppelin's ERC20 contract.

Here is the fixture:
```
@pytest.fixture(scope="session")
def oz(pm):
    project = pm("OpenZeppelin/openzeppelin-contracts@4.5.0/")
    return project
```
Brownie config:
```
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.5.0
dotenv: .env
compiler:
  solc:
    version: 0.8.9
    optimizer:
      enabled: true
      runs: 200
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"
      - "@openzeppelin-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.5.0"`
```
And the error:
```
    @pytest.fixture(scope="session")
    def oz(pm):
>       project = pm("OpenZeppelin/openzeppelin-contracts@4.5.0/")
E       ValueError: Dotenv specified in config but not found at path: ~/.brownie/packages/OpenZeppelin/openzeppelin-contracts@4.5.0/.env
```

Why is brownie trying to load an `.env` file from the package? any ideas on how to fix this, or is it a bug?
