### ISSUE TITLE
No such file or directory: 'ganache-cli'

### ISSUE THREAD

**Issue by kheyer** [eth-brownie/brownie#1520]
### Environment information

* `brownie` Version: v1.18.1
* `ganache` Version: v7.0.5
* `ganache/cli` Version: 0.1.6
* Python Version: 3.8.13
* OS: osx

### What was wrong?

I'm running into an issue with using a later version of Ganache that changed the default command from `ganache-cli` to `ganache`.  Trying to run anything in Brownie by default results in the error `No such file or directory: 'ganache-cli'`. 

One workaround I've found is to open another terminal session and run the `ganahce` command. Brownie is able to detect this.

While that works, I am trying to use the Ganache GUI as well, and I cannot get Brownie to connect to the Ganache GUI RPC without running into the `ganache-cli` issue.

Based off the information [here](https://eth-brownie.readthedocs.io/en/v1.0.0_a/test-rpc.html), I'm trying to use `brownie-config.yml` to set the new command line argument. I've added the following, but it doesnt seem to work

```
networks:
  development:
    test-rpc:
      cmd: "ganache"
      port: 7545
    host: "http://127.0.0.1:7545"
  ganache-local:
    cmd: "ganache"
    host: "http://127.0.0.1:7545"
    port: 7545
```

Am I correct in thinking this can be fixed by changing the `cmd` setting in the config? What is the correct way to do this?
