### ISSUE TITLE
London Fork support

### ISSUE THREAD

**Issue by SanctumVenture** [eth-brownie/brownie#1543]
Please add support to London fork

**Comment by WyseNynja** [comment]
What is currently not working for you? As long as your test node (ganache/hardhat) is configured for london, it should work fine.

**Comment by SanctumVenture** [comment]
got this

```
Brownie v1.18.2 - Python development framework for Ethereum

Compiling contracts...
  Solc version: 0.8.1
  Optimizer: Enabled  Runs: 1000
  EVM Version: London
CompilerError: solc returned the following errors:

Invalid EVM version requested.
```

brownie-config.yaml

```
compiler:
    evm_version: london
    solc:
        version: 0.8.1
        optimizer:
            enabled: true
            runs: 1000
        remappings: null
    vyper:
        version: null
```
