### ISSUE TITLE
Error publish_source with crossing remmapings

### ISSUE THREAD

**Issue by bcdevwork** [eth-brownie/brownie#1594]
### Environment information

* `brownie` Version: 1.18.1
* `ganache-cli` Version: 6.12.2
* `solc` Version: x.x.x
* Python Version: 3.8.9
* OS: osx

### What was wrong?

In projects with overlapping remappings publish_source returns an error:

FileNotFoundError: [Errno 2] No such file or directory: '/Users/user/.brownie/packages/OpenZeppelin/openzeppelin-contracts@4.4.2-upgradeable/contracts/token/ERC1155/IERC1155Upgradeable.sol'

The remap_import function checks the match in any order.

```yaml
compiler:
    solc:
        version: 0.8.11
        optimizer:
            enabled: true
        remappings:
        - "@openzeppelin-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.4.2"
        - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.2"

dependencies:
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.4.2
  - OpenZeppelin/openzeppelin-contracts@4.4.2 
```

### How can it be fixed?

I fix it in #1551
