### ISSUE TITLE
AttributeError: 'AttributeDict' object has no attribute 'baseFeePerGas' with Avalanche

### ISSUE THREAD

**Issue by JPFrancoia** [eth-brownie/brownie#1628]
### Environment information

* `brownie` Version: 1.19.2
* `ganache-cli` Version: 7.0.2
* `solc` Version: x.x.x
* Python Version: 3.10.5
* OS: Archlinux

### What was wrong?

I'm trying to set up a local fork of Avalanche, but my transfers/transactions fail with:

```
AttributeError: 'AttributeDict' object has no attribute 'baseFeePerGas'
```

Digging further, it looks like the chain doesn't have the `base_fee` attribute:

```
>>> chain.base_fee
  File "<console>", line 1, in <module>
  File "brownie/network/state.py", line 302, in base_fee
    return Wei(block.baseFeePerGas)
AttributeError: 'AttributeDict' object has no attribute 'baseFeePerGas'
```

Avalanche does have a base fee (https://docs.avax.network/quickstart/transaction-fees), so I don't understand what's going wrong here.

Here is how I setup the fork:

- The fork is made through docker-compose (and looking at the logs, the containers does start normally):

```yaml
version: "3.9"
services:
  ganache_avax:
    container_name: ganache_avax
    image: trufflesuite/ganache:v7.0.2
    ports:
      - 8545:8545
    command: >
      --fork.url https://api.avax.network/ext/bc/C/rpc
      --chain.hardfork istanbul
      --wallet.mnemonic brownie
      --fork.blockNumber 11730000
```

- I added the new network to brownie's networks: `brownie networks add Docker ganache-avax-fork host=http://127.0.0.1:8545 chainid=1337 explorer=https://api.snowtrace.io/api`

- I start brownie with: `brownie console --network ganache-avax-fork`

- Most of the commands work normally, I'm able to fetch contracts for example. But querying the `base_fee`  fails with the error above. All operations (e.g: transfers/transactions) that involve the base_fee fail.

### How can it be fixed?

I don't know :/
Is it the expected behaviour? Did I forget to set something?
