### ISSUE TITLE
anvil devnet cmd support

### ISSUE THREAD

**Issue by seinmyung25** [eth-brownie/brownie#1686]
### Overview
Provide a simple overview of what you wish to see added. Please include:

* What you are trying to do
`brownie console --network anvil`

* Why Brownie's current functionality is inadequate to address your goal
```
/Users/me/.pyenv/versions/3.10.10/lib/python3.10/site-packages/brownie/network/rpc/anvil.py:40: InvalidArgumentWarning: Ignoring invalid commandline setting for anvil: "evm_version" with value "istanbul".
  warnings.warn(

Launching 'anvil --port 8545'...
Brownie environment is ready.
>>>
```
### Specification
Describe the syntax and semantics of how you would like to see this feature implemented. The more detailed the better!
```
development:
  - name: Anvil
    id: anvil
    cmd: anvil
    host: http://127.0.0.1
    cmd_settings:
      evm_version: istanbul
      port: 8545
  - name: Anvil (Mainnet Fork)
    id: anvil-fork
    cmd: anvil
    host: http://127.0.0.1
    cmd_settings:
      evm_version: istanbul
      fork: mainnet
      port: 8545
```
Remember, your feature is much more likely to be included if it does not involve any breaking changes.
in `network/rpc/anvil.py`
CLI_FLAGS = {
    "port": "--port",
    "host": "--host",
    "fork": "--fork-url",
    "fork_block": "--fork-block-number",
    "chain_id": "--chain-id",
    "default_balance": "--balance",
    "gas_limit": "--gas-limit",
    "accounts": "--accounts",
    "evm_version": "--hardfork",
}

### Dependencies
Include links to any open issues that must be resolved before this feature can be implemented.
