### ISSUE TITLE
Make Brownie to run in a less privileged environment - Executes only with ROOT today

### ISSUE THREAD

**Issue by karmops** [eth-brownie/brownie#1690]
### Overview
Run an application that uses brownie in k8s using a security context
```yaml
securityContext:
  allowPrivilegeEscalation: false
  runAsUser: 10001
  runAsGroup: 10001
  capabilities:
    drop: ["ALL"]
```

### Specification
```yaml
securityContext:
  allowPrivilegeEscalation: false
  runAsUser: 10001
  runAsGroup: 10001
  capabilities:
    drop: ["ALL"]
```

### Result
![image](https://github.com/eth-brownie/brownie/assets/111905706/d997da97-8de4-4ad2-bb0f-eaf0d5e5d15c)

Brownie only executes with the root user
![image](https://github.com/eth-brownie/brownie/assets/111905706/28aa3502-4b86-4507-b2cd-11431ef00a73)

seems `cache.db` and `topics.json` are created during the Brownie initialization.
