### ISSUE TITLE
Couldnt not connect to ganache-cli in docker container 

### ISSUE THREAD

**Issue by GraphicalDot** [eth-brownie/brownie#701]
I have ganache-cli running in docker container, Remix can connect with it without any problems

```
(BrownieTest) ➜  application sudo netstat -tulpn 
[sudo] password for feynman: 
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      859/systemd-resolve 
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      934/cupsd           
tcp        0      0 127.0.0.1:40865         0.0.0.0:*               LISTEN      21662/code          
tcp6       0      0 ::1:631                 :::*                    LISTEN      934/cupsd           
tcp6       0      0 :::8545                 :::*                    LISTEN      28281/docker-proxy  
udp        0      0 127.0.0.53:53           0.0.0.0:*                           859/systemd-resolve 
udp        0      0 0.0.0.0:68              0.0.0.0:*                           1402/dhclient       
udp        0      0 0.0.0.0:631             0.0.0.0:*                           958/cups-browsed    
udp        0      0 224.0.0.251:5353        0.0.0.0:*                           19966/brave         
udp        0      0 224.0.0.251:5353        0.0.0.0:*                           19966/brave         
udp        0      0 224.0.0.251:5353        0.0.0.0:*                           19966/brave         
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           879/avahi-daemon: r 
udp        0      0 0.0.0.0:40781           0.0.0.0:*                           879/avahi-daemon: r 
udp6       0      0 :::5353                 :::*                                879/avahi-daemon: r 
udp6       0      0 :::43588                :::*                                879/avahi-daemon: r 
```

Testing again with HTTP command line tool on Unix
```
(BrownieTest) ➜  application http http://localhost:8545
/usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.25.3) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
HTTP/1.1 400 Bad Request
Connection: keep-alive
Content-Type: text/plain
Date: Tue, 28 Jul 2020 14:56:46 GMT
Transfer-Encoding: chunked

400 Bad Request
```
Now when I tried to run brownie console inside the virtual env, I am getting the following error
```
(BrownieTest) ➜  application brownie console
Brownie v1.10.3 - Python development framework for Ethereum

  File "brownie/_cli/__main__.py", line 56, in main
    importlib.import_module(f"brownie._cli.{cmd}").main()
  File "brownie/_cli/console.py", line 47, in main
    active_project.load_config()
  File "brownie/project/main.py", line 415, in load_config
    _load_project_config(self._path)
  File "brownie/_config.py", line 217, in _load_project_config
    _recursive_update(CONFIG.settings, config_data)
  File "brownie/_config.py", line 279, in _recursive_update
    _recursive_update(original[k], new[k])
  File "brownie/_config.py", line 279, in _recursive_update
    _recursive_update(original[k], new[k])
  File "brownie/_config.py", line 281, in _recursive_update
    original[k] = new[k]
TypeError: list indices must be integers or slices, not str
```
One more thing, Where I can find my brownie-config.yaml file, I have created in the same directory in which I ran brownie init call

```

project_structure:
    build: build
    contracts: contracts
    interfaces: interfaces
    reports: reports
    scripts: scripts
    tests: tests

networks:
    default: development
    development:
        gas_limit: max
        gas_price: 0
        reverting_tx_gas_limit: max
        default_contract_owner: true
        host: http://localhost
        cmd_settings:
          port: 8545
          gas_limit: 12000000
          accounts: 10
          evm_version: istanbul
          mnemonic: brownie
    live:
        gas_limit: auto
        gas_price: auto
        reverting_tx_gas_limit: false
        default_contract_owner: false



compiler:
    evm_version: null
    solc:
        version: null
        optimizer:
            enabled: true
            runs: 200
        remappings: null

console:
    show_colors: true
    color_style: monokai
    auto_suggest: true
    completions: true

reports:
    exclude_paths: null
    exclude_contracts: null

hypothesis:
    deadline: null
    max_examples: 50
    report_multiple_bugs: False
    stateful_step_count: 10
    phases:
        explicit: true
        reuse: true
        generate: true
        target: true
        shrink: true

autofetch_sources: false
dependencies: null
dev_deployment_artifacts: false
```
