### ISSUE TITLE
Contracts compiled with Brownie won't verify on Etherscan

### ISSUE THREAD

**Issue by Netherdrake** [eth-brownie/brownie#766]
### Environment information

* `brownie` Version: ==1.11.5
* `ganache-cli` Version: Ganache CLI v6.10.2 (ganache-core: 2.11.3)
* `solc` Version: Version: 0.6.12+commit.27d51765.Linux.g++
* Python Version: 3.8.2
* OS: ubuntu 20.04

### What was wrong?

For about half the contacts compiled and deployed via brownie I'm struggling to verify the bytecode on Etherscan. 

After deploying a contract with `Contract.deploy(...)` I would use [truffle-flattener](https://github.com/nomiclabs/truffle-flattener) to generate a single solidity file, and https://abi.hashex.org/ to re-create abi-encoded constructor arguments.

I made sure to always check the right compiler version and optimization params.

Here is my brownie config:
```
compiler:
  evm_version: null
  solc:
    version: 0.6.12
    optimizer:
      enabled: true
      runs: 200
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.1.0"
```

When I compile the same contract trough Remix (https://remix.ethereum.org/) it verifies without issues.

Compiled with Brownie:
https://etherscan.io/address/0xFD01f7a212eAa4aCAdB986fCb74951D510594c8E#code

Compiled with Remix:
https://etherscan.io/address/0x214f2421950de2ee4ff6a394ed677cf296efec0f#code

I really like Brownie and would like to use it to deploy contracts (instead of having to do them by hand via Remix). 
Any ideas for how to debug this?
