### ISSUE TITLE
Setting explorer URL for mainnet-fork

### ISSUE THREAD

**Issue by slaking** [eth-brownie/brownie#940]
What's the correct way to set explorer url in the config?

I tried this but it doesn't pick it up:

```
networks:
  default: mainnet-fork
  mainnet-fork:
    cmd_settings:
      fork: https://api.archivenode.io/...
    explorer: https://api.etherscan.io/api?apiKey=...

```

**Comment by iamdefinitelyahuman** [comment]
try setting `fork` with the name of another network, not with a network uri:

```
- cmd: ganache-cli
  cmd_settings:
    fork: mainnet
  host: http://127.0.0.1
  id: mainnet-fork
  ...
```

Then it will use the explorer from the network you're forking from
